### PR TITLE
Add flexbug 15

### PR DESCRIPTION
**Pull request by indrekpaas**

### CODE REVIEW

**Comment by philipwalton** [comment]
@gregwhitworth do you know anything about support for `<iframe>` elements as flex items or containers in Edge?

@indrekpaas the proposed workaround doesn't really cover a lot of cases. What if the flex container were in the column direction?

I wonder if this makes more sense as an addendum to [Flexbug 9](https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers)

**Comment by indrekpaas** [comment]
@philipwalton added examples with workarounds for column direction.

**Comment by philipwalton** [comment]
Hey @indrekpaas, I'm still not convinced this is a bug, at least not as presented in your example. To show you what I mean, if you change the `<iframe>` to a `<div>`, the `.FlexItemStretch` element shrinks to zero size, which means the original demo is depending on default properties of an `<iframe>` to work.

If this were a bug specific to `<iframe>`s, it should work as expected if you replace the element with a `<div>`.

**Comment by gregwhitworth** [comment]
Based on feedback from @philipwalton I'm closing this out.

**Pull request closed without merging**
