### PR TITLE
Add: Flex items always grow when they contain large images

### PR DESCRIPTION
**Pull request by tzi**
Hi @philipwalton!

I want to document this flexbug.
Is my description correct?

Thanks a lot for maintaining this repository,
Thomas.

### CODE REVIEW

**Comment by tzi** [comment]
It could be considered as a subcase of flexbug 1.

**Comment by gregwhitworth** [comment]
Crap @tzi I'm so sorry, I've gotten so used to just looking at the Issues tab I never glanced at the PRs. Firefox has shipped this fix in FF 47, but looking at the data at least from Statcounter 47 isn't hitting very high yet. Can you fix up the merge conflicts and then I'll read the bug in more detail and provide any terminology feedback. Thanks and again, sorry for the delay!

**Comment by gregwhitworth** [comment]
Welp, FF 47 has been out for a bit. Closing this out.

**Comment by tzi** [comment]
You've done right!

Thanks for all of your time.
Cheers.

**Pull request closed without merging**
