### PR TITLE
Flexbug 1 is fixed in WebKit Nightly

### PR DESCRIPTION
**Pull request by cvrebert**
See https://bugs.webkit.org/show_bug.cgi?id=146020#c27

### CODE REVIEW

**Comment by yisibl** [comment]
Nice!

**Comment by philipwalton** [comment]
So, I'm hesitant to include this because I've been reminded by Safari engineers time and time again that Webkit is not Safari and just because something is in Webkit doesn't mean it's necessarily going to be in Safari.

That being said, as long as we don't imply a fix date for Safari, maybe it's still worth pointing out. Thoughts?

**Comment by M4v3R** [comment]
@philipwalton Apple implemented this fix in [Safari Technology Preview](https://developer.apple.com/safari/technology-preview/), which means they will ship it with next stable release.

**Comment by philipwalton** [comment]
I'm still hesitant to mention this because, as far as I know, it's not tied to a specific version number. The point of saying when something was fixed is so, when people are looking at this list in the future, they'll be able to make a support determination.

Right now Safari TP is version 9.1.1 and Safari stable is 9.1. I think it's pretty unlikely that when this fix ships in Safari stable it'll still be version 9.1.1, and I think it's also likely that a new version of Safari could come out before this fix gets merged, at which point both browsers will increase their version numbers, and the 9.1.1 number will be wrong.

All that to say, until I'm convinced that saying "fixed in 9.1.1" is helpful and not misleading, I'd rather just wait until it's fixed in Safari stable.

**Comment by gregwhitworth** [comment]
I'm going to close this since it's dealing with issue 1 which Dean is already handling in another PR (https://github.com/philipwalton/flexbugs/pull/172).

**Pull request closed without merging**
