### PR TITLE
Flexbug 1: Link to Safari bug report

### LINKED ISSUE #13: Flexbug #1 is missing a WebKit/Safari tracking bug

### PR DESCRIPTION
**Pull request by cvrebert**
Fixes #13.

### CODE REVIEW

**Comment by philipwalton** [comment]
Thanks!

**Comment by cvrebert** [comment]
@philipwalton You're welcome. Do you happen to know if there's a WebKit bug report for Flexbug 11?

**Comment by philipwalton** [comment]
I found one that's pretty close, commented in the bug, and added it to the README via d4cff47c530837d152784768e3af3c304f79d3bc.

**Comment by cvrebert** [comment]
Many thanks :sparkles:

**Pull request merged**
