### PR TITLE
Add a bug minimum sizing and wrapping on Safari

### PR DESCRIPTION
**Pull request by tzi**
Hi!

Thanks for this curated list!
It's awesome :+1: 

I propose to add a annoying bug about `flex-wrap` on Safari (6, 7 & 8).

Cheers,
Thomas.

### CODE REVIEW

**Comment by philipwalton** [comment]
This appears to only be a problem because you're using prefixes and autoprefixer at the same time. If you remove autoprefixer it works as expected, and if you remove your prefixed properties it also works as expected.

**Comment by tzi** [comment]
Oh. That explains a lot! Thanks.

I made this mistake when looking for the minimum use case.

So the bug is more specific: There is no wrapping when a flex item has a `min-width` and a percent `flex-basis`.
See the updated demo: http://codepen.io/tzi/pen/rVmbvK

I reproduced this on Safari 8, 7, 6.1 and 6.
I did not found a workaround.
Are you interested by documenting this bug?

Cheers,
Thomas.

**Comment by philipwalton** [comment]
Hmm, yeah that definitely seems like a bug. But without a workaround, I'm not sure it should go in the README. Hopefully having it here will help someone else find it.

**Comment by tzi** [comment]
OK :)

I think knowing this kind of bugs could help people to not use flexbox in some cases.
So let me know if you change your mind.

Thanks again for the sharing!
Thomas.

**Comment by jpdevries** [comment]
> So the bug is more specific: There is no wrapping when a flex item has a min-width and a percent flex-basis.

I was also able to reproduce this in Webkit nightly (which recently un-prefixed flexbox properties).

**Comment by philipwalton** [comment]
> I think knowing this kind of bugs could help people to not use flexbox in some cases.

I agree that knowing this kind of thing is useful, but since it only affects a small subset of situations, I'd hate to discourage people from using flexbox (in general) for a bug that they very well may never encounter in the wild.

If we can come up with a workaround for this that doesn't involve using `inline-block`, I'd be happy to include it.

**Comment by jpdevries** [comment]
`display:inline-block` doesn't seem to have an affect either way.

FWIW I spent some time trying to come up with a work around and really just found another way to experience the same issue. In [this pen](http://codepen.io/jpdevries/pen/GJEjJa) notice that the issue is reproducible _without a percentage flex-basis_ and with a percentage based width.

##### Workaround for Fixed-Width flex parents
This only works on flex parents with a fixed width so it isn't a flexible enough work around but for your pen you could do:

```scss
.FlexItem {
  flex: 1 0 (400px * 0.3);
}
```

**Comment by tzi** [comment]
> I was also able to reproduce this in Webkit nightly (which recently un-prefixed flexbox properties).

That's really bad news :'(

> If we can come up with a workaround for this that doesn't involve using inline-block, I'd be happy to include it.

I will keep looking for a workaround... but there is few chances ;)

**Comment by tzi** [comment]
For the record, this bug is now reported as flexbug 12, thanks to 45e9327.

**Pull request closed without merging**
