### PR TITLE
added relative padding bug

### PR DESCRIPTION
**Pull request by bloodyowl**

### CODE REVIEW

**Comment by philipwalton** [comment]
This seems to be true for margin as well, and it seems to only affect the vertical direction:
http://codepen.io/anon/pen/mJyyEV

**Comment by philipwalton** [comment]
Have you filed a bug on www.bugzilla.org?

**Comment by bloodyowl** [comment]
no, I didn't yet.

**Comment by philipwalton** [comment]
Can you update this to mention margins as well and point out that it only affects the vertical direction? Then I'll merge it in.

**Comment by bloodyowl** [comment]
fixed & rebased

**Comment by philipwalton** [comment]
Thanks. I'll probably update the demos a bit and fork them to my account.

**Pull request merged**
