### PR TITLE
Flexbox bug in IE11: Justify-content: space-around 

### PR DESCRIPTION
**Pull request by hgberman**
I think I may have found a new flexbox bug. I have a flex container that is too small to hold the flex items. I am using the CSS property "justify-content: space-around". 

According to the specs, the packed items should break out of the container and overflow equally on both sides. That is, it should behave just like "justify-content: center". And that happens with Chrome and Firefox.

But with Internet Explorer 11, the packed items start inside the left edge of the flex container and only break out on the right side. It behaves like "justify-content: flex-start". This is not what is described in the specs at: https://drafts.csswg.org/css-flexbox/#justify-content-property .

Here's the code:

<style>
        html {
            box-sizing: border-box;
        }

        *, *:before, *:after {
            box-sizing: inherit;
        }

        .container {
            background-color: wheat;
            font-size: 2rem;
            font-family: arial;
            font-weight: bold;
            width: 310px;
        }

        .item {
            padding: 10px;
            color: white;
        }    

        .color1 {background-color: red;}
        .color2 {background-color: green;}
        .color3 {background-color: blue;}
        .color4 {background-color: indigo;}
        .color5 {background-color: violet;} 
        .color6 {background-color: darkslategray;}

        .container {
            margin: 5px 50px;
            width: 150px;
            padding: 10px 0px;
        }

        .container-flex {
            display: flex;
            justify-content: space-around; /* Identical to center */
        }
    </style>

    <div class="container container-flex">
        <span class="item color1">1</span>
        <span class="item color2">2</span>
        <span class="item color3">3</span>
        <span class="item color4">4</span>
        <span class="item color5">5</span>
        <span class="item color6">6</span>
    </div>

### CODE REVIEW

**Comment by philipwalton** [comment]
Something is wrong here. Can you please rebase against `master` so I can see what's actually changed? Currently the diff is showing against a very old commit.

**Comment by hgberman** [comment]
Hi,

I think you're doing a great job collating info about flexbox bugs. I was
trying to alert you about a possible bug in my recent communication.
Apparently, something was wrong with the communication at GitHub, and you
weren't about to read my comment or didn't understand what I was talking
about. Probably my fault since I was having trouble getting things to work
on GitHub.

I'm just a beginner and don't understand what you asked me to do in your
reply. I don't know what it means to rebase against master, don't know what
the diff is, and don't know what an old commit is. So here in this memo,
I'll describe the bug I think I've found and hope that everything is clear.


Here's what's happening. I am using the CSS declaration "justify-content:
space-around" with a single-row flex container. The flex items are too big
to be contained within one row of the container. According to the Worldwide
Web Consortium, we should see the flex items packed, centered, and
overflowing the too-small container *on both sides*. And this is what
occurs with Firefox and Chrome, as shown below.

[image: Inline image 1]

But it doesn’t work this way with Internet Explorer 11 – at least not on my
computer. With Internet Explorer 11, the items start along the left edge of
the container and break out of the container *only on the right side*, as
shown below:


[image: Inline image 2]


This is not what we would expect with “justify-content: space-around”,
based on the Worldwide Web Consortium specs at
https://drafts.csswg.org/css-flexbox/#justify-content-property). When I
noticed this issue with Internet Explorer 11, I thought Internet Explorer
11 might have a bug. And I thought maybe it should be added to the list of
bugs at https://github.com/philipwalton/flexbugs. So I notified you.


Let me know if this is a bug or if I'm just doing something wrong or if you
need any other info from me. Thanks.


Harvey


p.s. In case it helps, here's the code that produced the above results:


<style>

        html {

            box-sizing: border-box;

        }


        *, *:before, *:after {

            box-sizing: inherit;

        }


        .container {

            background-color: wheat;

            font-size: 66px;

            font-family: arial;

            font-weight: bold;

            width: 900px;

            margin: 30px auto;

            text-align:center;

            border: solid 1px brown;

            padding:10px 0;

        }


        .item {

            padding: 10px;

            color: white;

            border-radius: 50px;

            height: 200px;

            min-width: 200px;

            padding-top:66px;

        }


        .color1 {background-color: red;}

        .color2 {background-color: green;}

        .color3 {background-color: blue;}

        .color4 {background-color: indigo;}

        .color5 {background-color: violet;}

        .color6 {background-color: darkslategray;}


        .container-flex {

            display: flex;

            justify-content: space-around; /* Identical to center */

        }

    </style>


    <div class="container container-flex">

        <span class="item color1">1</span>

        <span class="item color2">2</span>

        <span class="item color3">3</span>

        <span class="item color4">4</span>

        <span class="item color5">5</span>

        <span class="item color6">6</span>

    </div>

**Comment by philipwalton** [comment]
You opened this as a pull request, which means you're trying to submit code to this repo. If you're just trying to ask a question or report a bug, you can open an issue instead. Did you mean to submit a pull request?

**Comment by hgberman** [comment]
I did mean to report a bug, rather than submit a pull request. I opened an
issue, as you suggested.

Sorry for the confusion.

**Pull request closed without merging**
